openapi: 3.0.1
info:
  title: Transactions
  version: "1.0"
servers:
 -
  url: /
security:
 -
  default: []
paths:
  /initiation:
    post:
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - api_key
         - oauth2
        optional: false
  /execution:
    post:
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          description: ok
      security:
       -
        default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
         - api_key
         - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
          scopes: {}
x-wso2-api-key-header: ApiKey
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
   - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
   - authorization
   - Access-Control-Allow-Origin
   - Content-Type
   - SOAPAction
   - apikey
   - Internal-Key
  accessControlAllowMethods:
   - GET
   - PUT
   - POST
   - DELETE
   - PATCH
   - OPTIONS
x-wso2-production-endpoints:
  urls:
   - http://localhost:8082/transactions/transfer
  type: http
x-wso2-sandbox-endpoints:
  urls:
   - http://localhost:8082/transactions/transfer
  type: http
x-wso2-basePath: /transactions/1.0
x-wso2-transports:
 - http
 - https
x-wso2-application-security:
  security-types:
   - api_key
   - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
