
services:
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CLUSTER_ID: "IXs3fwweTZ6vUjgprDdWhg"
      CLUSTER_ID: "IXs3fwweTZ6vUjgprDdWhg"
    mem_limit: 1g

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    mem_limit: 512m
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql 
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
     interval: 10s
     timeout: 5s
     retries: 5

  wso2am:
    image: wso2/wso2am:latest
    container_name: wso2am
    ports:
      - "9443:9443"
      - "9763:9763"
    depends_on:
      - mysql
      - kafka
    mem_limit: 1.5g
 
  user:
    build:
      context: .
      dockerfile: Dockerfile-jdk21
      args:
       SERVICE: user-service
    container_name: user-service
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - mysql
      - kafka
    ports:
      - "8080:8080" 
    mem_limit: 512m
  
  transaction:
    build:
      context: .
      dockerfile: Dockerfile-jdk17
      args:
       SERVICE: transaction-service
    container_name: transaction-service
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - mysql
      - kafka
    ports:
      - "8082:8080" 
    mem_limit: 512m
  
  account:
    build:
      context: .
      dockerfile: Dockerfile-jdk21
      args:
       SERVICE: account-service
    container_name: account-service
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - mysql
      - kafka
    ports:
      - "8084:8080" 
    mem_limit: 512m
  
  bff:
    build:
      context: .
      dockerfile: Dockerfile-jdk21
      args:
       SERVICE: bff-service
    container_name: bff-service
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - mysql
      - kafka
    ports:
      - "8085:8080" 
    mem_limit: 512m
  
  logging:
    build:
      context: .
      dockerfile: Dockerfile-jdk21
      args:
       SERVICE: logging-service
    container_name: logging-service
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    depends_on:
      - mysql
      - kafka
    ports:
      - "8086:8080" 
    mem_limit: 512m

volumes:
  mysql_data:
  
