spring:
  application:
    name: logging-service

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: logging-consumer-group
      auto-offset-reset: earliest
      properties:
        "[spring.json.trusted.packages]": "*"
  h2:
    console:
      enabled: true       # Enable the H2 web console
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:loggingdb   # for dev/testing
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8086  

